#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','l','i','n','u',
        'x','-','a','n','d','r','o','i','d','e','a','b','i','-','g','c','c','\0'
    };
    #define PLATFORM "platform: -I."
    #define DATE "built on: Thu Mar 31 10:04:27 2016"
#endif
