/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exponent_openssl_EcKeyPair */

#ifndef _Included_com_exponent_openssl_EcKeyPair
#define _Included_com_exponent_openssl_EcKeyPair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exponent_openssl_EcKeyPair
 * Method:    generate
 * Signature: (I)Lcom/exponent/openssl/EcKeyPair;
 */
JNIEXPORT jobject JNICALL Java_com_exponent_openssl_EcKeyPair_generate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_exponent_openssl_EcKeyPair
 * Method:    checkKey
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_exponent_openssl_EcKeyPair_checkKey
  (JNIEnv *, jobject);

/*
 * Class:     com_exponent_openssl_EcKeyPair
 * Method:    getEcdhKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_exponent_openssl_EcKeyPair_getEcdhKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
