/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_exponent_openssl_EcKeyPair.h"
/* Header for class com_exponent_openssl_Cmac */

#ifndef _Included_com_exponent_openssl_Cmac
#define _Included_com_exponent_openssl_Cmac
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exponent_openssl_Cmac
 * Method:    generate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exponent_openssl_Cmac_generate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
